spring.application.name=payments

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000/realms/master
openweathermap.api-key=
spring.ai.mcp.server.protocol=STREAMABLE

## Actuator endpoints
## Source - https://stackoverflow.com/a/77894697
## Posted by Mar-Z, modified by community. See post 'Timeline' for change history
## Retrieved 2026-08-16, License - CC BY-SA 4.0
management.endpoints.web.exposure.include=*

## H2 Database config
spring.datasource.url=jdbc:h2:mem:paymentsdb
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.hibernate.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.h2.console.enabled=true
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.h2.console.path=/h2-console

## Logging
logging.level.org.springframework.web=DEBUG