# Activated with SPRING_PROFILES_ACTIVE=docker (see docker-compose.yml)
spring.datasource.url=jdbc:oracle:thin:@//oracle-db:1521/ORCLPDB1
spring.data.redis.host=redis

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka

opa.url=http://opa:8181