spring.application.name=payments
server.port=8080
app.db-enabled=false

openweathermap.api-key=

spring.cloud.gateway.httpclient.connect-timeout=2000
spring.cloud.gateway.httpclient.response-timeout=6s
# Programmatic route is defined in RouteConfig.java.
# If you prefer YAML/properties routes instead, remove RouteConfig and define here.

spring.datasource.url=${DB_URL:jdbc:oracle:thin:@//localhost:1521/ORCLPDB1}
spring.datasource.username=${DB_USERNAME:gateway_app}
spring.datasource.password=${DB_PASSWORD:changeit}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=true

#jwt.jwk-set-uri=${JWT_JWK_SET_URI:http://localhost:9000/.well-known/jwks.json}
jwt.jwk-set-uri=http://localhost:9000/realms/master/protocol/openid-connect/certs

opa.url=${OPA_URL:http://localhost:8181}

resilience4j.circuitbreaker.instances.paymentServiceCB.slidingWindowType=TIME_BASED
resilience4j.circuitbreaker.instances.paymentServiceCB.slidingWindowSize=10
resilience4j.circuitbreaker.instances.paymentServiceCB.minimumNumberOfCalls=50
resilience4j.circuitbreaker.instances.paymentServiceCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.paymentServiceCB.waitDurationInOpenState=15s
resilience4j.circuitbreaker.instances.paymentServiceCB.permittedNumberOfCallsInHalfOpenState=10
resilience4j.circuitbreaker.instances.paymentServiceCB.automaticTransitionFromOpenToHalfOpenEnabled=true

resilience4j.timelimiter.instances.paymentServiceCB.timeoutDuration=6s

management.endpoints.web.exposure.include=health,info,gateway,circuitbreakers
management.endpoint.health.show-details=always