spring.application.name=my-tools-api

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:9000/realms/master
openweathermap.api-key=
spring.ai.mcp.server.protocol=STREAMABLE

## Source - https://stackoverflow.com/a/77894697
## Posted by Mar-Z, modified by community. See post 'Timeline' for change history
## Retrieved 2026-08-16, License - CC BY-SA 4.0
management.endpoints.web.exposure.include=*